# Site settings
title: Thoughts on Development
email: garciarjaime+blog@gmail.com
description: "Sharing thoughts on software development"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
